require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PizzatoppingsController do

  # This should return the minimal set of attributes required to create a valid
  # Pizzatopping. As you add validations to Pizzatopping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "topping_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PizzatoppingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pizzatoppings as @pizzatoppings" do
      pizzatopping = Pizzatopping.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pizzatoppings).should eq([pizzatopping])
    end
  end

  describe "GET show" do
    it "assigns the requested pizzatopping as @pizzatopping" do
      pizzatopping = Pizzatopping.create! valid_attributes
      get :show, {:id => pizzatopping.to_param}, valid_session
      assigns(:pizzatopping).should eq(pizzatopping)
    end
  end

  describe "GET new" do
    it "assigns a new pizzatopping as @pizzatopping" do
      get :new, {}, valid_session
      assigns(:pizzatopping).should be_a_new(Pizzatopping)
    end
  end

  describe "GET edit" do
    it "assigns the requested pizzatopping as @pizzatopping" do
      pizzatopping = Pizzatopping.create! valid_attributes
      get :edit, {:id => pizzatopping.to_param}, valid_session
      assigns(:pizzatopping).should eq(pizzatopping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pizzatopping" do
        expect {
          post :create, {:pizzatopping => valid_attributes}, valid_session
        }.to change(Pizzatopping, :count).by(1)
      end

      it "assigns a newly created pizzatopping as @pizzatopping" do
        post :create, {:pizzatopping => valid_attributes}, valid_session
        assigns(:pizzatopping).should be_a(Pizzatopping)
        assigns(:pizzatopping).should be_persisted
      end

      it "redirects to the created pizzatopping" do
        post :create, {:pizzatopping => valid_attributes}, valid_session
        response.should redirect_to(Pizzatopping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pizzatopping as @pizzatopping" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pizzatopping.any_instance.stub(:save).and_return(false)
        post :create, {:pizzatopping => { "topping_id" => "invalid value" }}, valid_session
        assigns(:pizzatopping).should be_a_new(Pizzatopping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pizzatopping.any_instance.stub(:save).and_return(false)
        post :create, {:pizzatopping => { "topping_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pizzatopping" do
        pizzatopping = Pizzatopping.create! valid_attributes
        # Assuming there are no other pizzatoppings in the database, this
        # specifies that the Pizzatopping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pizzatopping.any_instance.should_receive(:update).with({ "topping_id" => "1" })
        put :update, {:id => pizzatopping.to_param, :pizzatopping => { "topping_id" => "1" }}, valid_session
      end

      it "assigns the requested pizzatopping as @pizzatopping" do
        pizzatopping = Pizzatopping.create! valid_attributes
        put :update, {:id => pizzatopping.to_param, :pizzatopping => valid_attributes}, valid_session
        assigns(:pizzatopping).should eq(pizzatopping)
      end

      it "redirects to the pizzatopping" do
        pizzatopping = Pizzatopping.create! valid_attributes
        put :update, {:id => pizzatopping.to_param, :pizzatopping => valid_attributes}, valid_session
        response.should redirect_to(pizzatopping)
      end
    end

    describe "with invalid params" do
      it "assigns the pizzatopping as @pizzatopping" do
        pizzatopping = Pizzatopping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pizzatopping.any_instance.stub(:save).and_return(false)
        put :update, {:id => pizzatopping.to_param, :pizzatopping => { "topping_id" => "invalid value" }}, valid_session
        assigns(:pizzatopping).should eq(pizzatopping)
      end

      it "re-renders the 'edit' template" do
        pizzatopping = Pizzatopping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pizzatopping.any_instance.stub(:save).and_return(false)
        put :update, {:id => pizzatopping.to_param, :pizzatopping => { "topping_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pizzatopping" do
      pizzatopping = Pizzatopping.create! valid_attributes
      expect {
        delete :destroy, {:id => pizzatopping.to_param}, valid_session
      }.to change(Pizzatopping, :count).by(-1)
    end

    it "redirects to the pizzatoppings list" do
      pizzatopping = Pizzatopping.create! valid_attributes
      delete :destroy, {:id => pizzatopping.to_param}, valid_session
      response.should redirect_to(pizzatoppings_url)
    end
  end

end
